'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, Float, MeshTransmissionMaterial, Stars } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';

function EV(){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.35});return <group ref={g} scale={1.3}><mesh position={[0,0,0]}><boxGeometry args={[3.2,.55,1.25]}/><meshStandardMaterial color="#aeeaff" metalness={.8} roughness={.18}/></mesh><mesh position={[-.9,.42,0]}><boxGeometry args={[1.2,.55,1.05]}/><meshStandardMaterial color="#eef8ff" metalness={.5} roughness={.1}/></mesh>{[-1.1,1.1].map(x=>[-.68,.68].map((z,i)=><mesh key={x+z} position={[x,-.42,z]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.24,.08,16,48]}/><meshStandardMaterial color="#080c14" metalness={.9}/></mesh>))}</group>}
function Watch(){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.6});return <group ref={g}><mesh><torusGeometry args={[.9,.16,32,96]}/><meshStandardMaterial color="#d8e8ff" metalness={.9} roughness={.12}/></mesh><mesh><cylinderGeometry args={[.62,.62,.16,64]}/><meshStandardMaterial color="#091324"/></mesh><mesh position={[0,.09,0]}><circleGeometry args={[.48,64]}/><meshStandardMaterial color="#7dd3fc" emissive="#38bdf8" emissiveIntensity={1.5}/></mesh></group>}
function Camera(){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.45});return <group ref={g}><mesh><boxGeometry args={[1.7,1.05,.55]}/><meshStandardMaterial color="#e8f7ff" metalness={.75} roughness={.16}/></mesh><mesh position={[0,0,.35]}><cylinderGeometry args={[.38,.38,.36,64]}/><meshStandardMaterial color="#020817" metalness={.8}/></mesh><mesh position={[0,0,.57]}><circleGeometry args={[.22,64]}/><meshStandardMaterial color="#60a5fa" emissive="#2563eb" emissiveIntensity={2}/></mesh></group>}
function Thermo(){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.45});return <group ref={g}><mesh><torusGeometry args={[.9,.18,32,128]}/><meshStandardMaterial color="#a7f3d0" metalness={.9} roughness={.1}/></mesh><mesh><circleGeometry args={[.65,96]}/><meshStandardMaterial color="#07111f"/></mesh><mesh position={[0,0,.04]}><ringGeometry args={[.42,.47,96]}/><meshStandardMaterial color="#22d3ee" emissive="#22d3ee" emissiveIntensity={1.8}/></mesh></group>}
function Hub(){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.35});return <group ref={g}><mesh><cylinderGeometry args={[.8,.95,1.25,64]}/><MeshTransmissionMaterial thickness={.4} roughness={.15} transmission={.55} color="#dff8ff"/></mesh><mesh position={[0,.72,0]}><torusGeometry args={[.78,.035,16,128]}/><meshStandardMaterial color="#67e8f9" emissive="#22d3ee" emissiveIntensity={2}/></mesh></group>}
function ProductMesh({type}:{type:string}){return <Float speed={2.2} rotationIntensity={.55} floatIntensity={.9}>{type==='ev'?<EV/>:type==='watch'?<Watch/>:type==='camera'?<Camera/>:type==='thermo'?<Thermo/>:<Hub/>}</Float>}
export default function ProductScene({type='ev'}:{type?:string}){return <Canvas camera={{position:[0,0,5],fov:45}}><ambientLight intensity={.7}/><pointLight position={[4,5,6]} intensity={2.5}/><spotLight position={[-4,3,4]} angle={.35} intensity={2}/><Stars radius={80} depth={40} count={1400} factor={3}/><ProductMesh type={type}/><Environment preset="city"/></Canvas>}
