server:
  port: 8080
spring:
  application:
    name: helios-connected-experience-platform
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
